### ISSUE TITLE
[Roadmap] Updateto ES6 syntax

### ISSUE THREAD

**Issue by neighborhood999** [EragonJ/Kaku#409]
Ref: #408 
- [x] ├── bootup.js
- [x] ├── src
- [x] │   ├── main.js
- [x] │   ├── modules
- [x] │   │   ├── AppCore.js
- [x] │   │   ├── AutoUpdater.js
- [x] │   │   ├── backuper
- [x] │   │   │   ├── DropboxBackuper.js
- [x] │   │   │   └── LocalBackuper.js
- [x] │   │   ├── Constants.js
- [x] │   │   ├── Database.js
- [x] │   │   ├── DownloadManager.js
- [x] │   │   ├── HistoryManager.js
- [x] │   │   ├── importer
- [x] │   │   │   └── YoutubeImporter.js
- [x] │   │   ├── L10nManager.js
- [x] │   │   ├── NewsFetcher.js
- [x] │   │   ├── PlaylistManager.js
- [x] │   │   ├── PreferenceManager.js
- [x] │   │   ├── Searcher.js
- [x] │   │   ├── Tracker.js
- [x] │   │   └── wrapper
- [x] │   │       ├── Dropbox.js
- [x] │   │       ├── Firebase.js
- [x] │   │       └── Youtube.js
- [x] │   ├── public
- [x] │   └── views
- [x] │       ├── components
- [x] │       │   ├── about
- [x] │       │   │   └── index.js
- [x] │       │   ├── alltracks
- [x] │       │   │   └── index.js
- [x] │       │   ├── chatroom
- [x] │       │   │   ├── comment
- [x] │       │   │   │   ├── comment-form.js
- [x] │       │   │   │   ├── comment.js
- [x] │       │   │   │   ├── comment-list.js
- [x] │       │   │   │   └── comment-no-data.js
- [ ] │       │   │   └── index.js
- [x] │       │   ├── connection-check
- [x] │       │   │   └── index.js
- [x] │       │   ├── history
- [x] │       │   │   └── index.js
- [x] │       │   ├── menus
- [x] │       │   │   └── index.js
- [x] │       │   ├── news
- [x] │       │   │   ├── index.js
- [x] │       │   │   └── news-tag.js
- [x] │       │   ├── online-dj
- [x] │       │   │   ├── choose-role-page.js
- [ ] │       │   │   ├── dashboard-page.js
- [x] │       │   │   └── index.js
- [x] │       │   ├── player
- [x] │       │   │   ├── control-buttons.js
- [x] │       │   │   ├── index.js
- [x] │       │   │   └── track.js
- [x] │       │   ├── playlist
- [x] │       │   │   └── index.js
- [x] │       │   ├── searchbar
- [x] │       │   │   └── index.js
- [x] │       │   ├── settings
- [x] │       │   │   └── index.js
- [x] │       │   ├── shared
- [x] │       │   │   ├── action-button.js
- [x] │       │   │   ├── l10n-span.js
- [x] │       │   │   ├── track
- [x] │       │   │   │   ├── no-track.js
- [x] │       │   │   │   ├── track.js
- [x] │       │   │   │   ├── track-list.js
- [x] │       │   │   │   └── track-square.js
- [x] │       │   │   ├── track-mode-button.js
- [x] │       │   │   └── tracks.js
- [x] │       │   ├── toolbar
- [x] │       │   │   └── index.js
- [x] │       │   └── topranking
- [x] │       │       └── index.js
- [x] │       └── modules
- [x] │           ├── AppMenus.js
- [x] │           ├── CastingManager.js
- [x] │           ├── Dialog.js
- [x] │           ├── EasterEggs.js
- [x] │           ├── KonamiCodeManager.js
- [x] │           ├── Notifier.js
- [ ] │           ├── Player.js
- [x] │           ├── RemotePlayer.js
- [x] │           └── TabManager.js
- [ ] └── webpack.config.js

**Comment by EragonJ** [comment]
@neighborhood999 we don't need to do that all in one PR, we can make several PRs for them to make sure things are not going wrong. And by the way, I'll keep moving out some shared scripts to `Kaku-core` to make sure server side can reuse them too.

**Comment by neighborhood999** [comment]
Yep, I know. I think need step by step update those code, because we need make sure work fine.

> I am also refactoring codebase now and I don't want you to solve several conflicts ! 

Your means it's you will refactor code and if have any conflict, let your solve? :smiley:

**Comment by EragonJ** [comment]
> Means you will refactor code and if have any conflict, let your solve? 😃

I mean because I am also refactoring some codes, so it would be better that you provide PR as soon as possible if you already finished any script. Otherwise, if we are both changing the same scripts, you may need to solve the conflicts sometimes.

And let's focus on `components` and `modules` first, we can ignore tests for the time being :)

**Comment by neighborhood999** [comment]
Haha, Sorry! I misunderstood your means.

**Comment by EragonJ** [comment]
just updated the checkboxes, quite close to the goal 🤔

**Comment by neighborhood999** [comment]
@EragonJ Looks Greattt!

**Comment by neighborhood999** [comment]
Most modules already rewrite by ES6 syntax.

**Comment by EragonJ** [comment]
@neighborhood999 +++++++ big thanks !
